esp-hal-smartled: update transmit API usage
esp-hal-smartled expects esp-hal version 1.0.0. Using a more recent
version raises the following build failure:

   Compiling esp-hal-smartled v0.17.0
(/home/alexis/src/neon-beat/esp-hal-community/esp-hal-smartled)
error[E0277]: `?` couldn't convert the error to `LedAdapterError`
   -->
/home/alexis/src/neon-beat/esp-hal-community/esp-hal-smartled/src/lib.rs:262:48
    |
262 |         match channel.transmit(self.rmt_buffer)?.wait() {
    |                       -------------------------^ the trait
`From<(esp_hal::rmt::Error, esp_hal::rmt::Channel<'_, Blocking,
esp_hal::rmt::Tx>)>` is not implemented for `LedAdapterError`
    |                       |
    |                       this can't be annotated with `?` because it
has type `Result<_, (esp_hal::rmt::Error, esp_hal::rmt::Channel<'_,
Blocking, esp_hal::rmt::Tx>)>`
    |
note: `LedAdapterError` needs to implement `From<(esp_hal::rmt::Error,
esp_hal::rmt::Channel<'_, Blocking, esp_hal::rmt::Tx>)>`
   -->
/home/alexis/src/neon-beat/esp-hal-community/esp-hal-smartled/src/lib.rs:68:1
    |
 68 | pub enum LedAdapterError {
    | ^^^^^^^^^^^^^^^^^^^^^^^^
    = note: the question mark operation (`?`) implicitly performs a
conversion on the error value using the `From` trait
    = help: the trait `From<(esp_hal::rmt::Error,
esp_hal::rmt::Channel<'_, Blocking, esp_hal::rmt::Tx>)>` is not
implemented for `LedAdapterError`
            but trait `From<esp_hal::rmt::Error>` is implemented for it
    = help: for that trait implementation, expected
`esp_hal::rmt::Error`, found `(esp_hal::rmt::Error,
esp_hal::rmt::Channel<'_, Blocking, esp_hal::rmt::Tx>)`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `esp-hal-smartled` (lib) due to 1 previous
error

This break has been introduced by commit 240afa9ac996 ("RMT:
Various cleanups, small API enhancements (#4302)"), which updated some
Channel methods to stop consuming the channel on error and rather
returning it. Fix this API usage by applying the same kind of mapping
that has been introduced internally in esp-hal.

Signed-off-by: Alexis Lothoré <alexis.lothore@gmail.com>