esp-hal-smartled: update esp-hal API usage
esp-hal-smartled currently expects esp-hal 1.0.0. There are currently no
higher version published, but trying to build the crate against upstream
esp-hal (from github) gives the following errors:

error[E0061]: this method takes 1 argument but 2 arguments were supplied
    -->
/home/alexis/src/cargo/git/checkouts/esp-hal-community-de8617117b5b9cf9/8a8734c22b6c/esp-hal-smartled/src/lib.rs:217:31
     |
 208 |     pub fn new_with_color<C, O>(
     |                              - found this type parameter
...
 217 |         let channel = channel.configure_tx(pin,
led_config()).unwrap();
     |                               ^^^^^^^^^^^^      ------------
unexpected argument #2 of type `TxChannelConfig`
     |
note: expected `&TxChannelConfig`, found type parameter `O`
    -->
/home/alexis/src/cargo/git/checkouts/esp-hal-community-de8617117b5b9cf9/8a8734c22b6c/esp-hal-smartled/src/lib.rs:217:44
     |
 217 |         let channel = channel.configure_tx(pin,
led_config()).unwrap();
     |                                            ^^^
     = note:   expected reference `&TxChannelConfig`
             found type parameter `O`
note: method defined here
    -->
/home/alexis/src/cargo/git/checkouts/esp-hal-29ef8683203c9b81/223815270092/esp-hal/src/rmt.rs:1294:8
     |
1294 |     fn configure_tx(self, config: &TxChannelConfig) ->
Result<Channel<'ch, Dm, Tx>, Error>
     |        ^^^^^^^^^^^^
help: remove the extra argument
     |
 217 -         let channel = channel.configure_tx(pin,
led_config()).unwrap();
 217 +         let channel = channel.configure_tx(/* &TxChannelConfig
*/).unwrap();
     |

error[E0277]: `?` couldn't convert the error to `LedAdapterError`
   -->
/home/alexis/src/cargo/git/checkouts/esp-hal-community-de8617117b5b9cf9/8a8734c22b6c/esp-hal-smartled/src/lib.rs:262:48
    |
262 |         match channel.transmit(self.rmt_buffer)?.wait() {
    |                       -------------------------^ the trait
`From<(esp_hal::rmt::Error, esp_hal::rmt::Channel<'_, Blocking,
esp_hal::rmt::Tx>)>` is not implemented for `LedAdapterError`
    |                       |
    |                       this can't be annotated with `?` because it
has type `Result<_, (esp_hal::rmt::Error, esp_hal::rmt::Channel<'_,
Blocking, esp_hal::rmt::Tx>)>`
    |
note: `LedAdapterError` needs to implement `From<(esp_hal::rmt::Error,
esp_hal::rmt::Channel<'_, Blocking, esp_hal::rmt::Tx>)>`
   -->
/home/alexis/src/cargo/git/checkouts/esp-hal-community-de8617117b5b9cf9/8a8734c22b6c/esp-hal-smartled/src/lib.rs:68:1
    |
 68 | pub enum LedAdapterError {
    | ^^^^^^^^^^^^^^^^^^^^^^^^
    = note: the question mark operation (`?`) implicitly performs a
conversion on the error value using the `From` trait
    = help: the trait `From<(esp_hal::rmt::Error,
esp_hal::rmt::Channel<'_, Blocking, esp_hal::rmt::Tx>)>` is not
implemented for `LedAdapterError`
            but trait `From<esp_hal::rmt::Error>` is implemented for it
    = help: for that trait implementation, expected
`esp_hal::rmt::Error`, found `(esp_hal::rmt::Error,
esp_hal::rmt::Channel<'_, Blocking, esp_hal::rmt::Tx>)`

error[E0061]: this method takes 1 argument but 2 arguments were supplied
    -->
/home/alexis/src/cargo/git/checkouts/esp-hal-community-de8617117b5b9cf9/8a8734c22b6c/esp-hal-smartled/src/lib.rs:335:31
     |
 326 |     pub fn new_with_color<C, O>(
     |                              - found this type parameter
...
 335 |         let channel = channel.configure_tx(pin,
led_config()).unwrap();
     |                               ^^^^^^^^^^^^      ------------
unexpected argument #2 of type `TxChannelConfig`
     |
note: expected `&TxChannelConfig`, found type parameter `O`
    -->
/home/alexis/src/cargo/git/checkouts/esp-hal-community-de8617117b5b9cf9/8a8734c22b6c/esp-hal-smartled/src/lib.rs:335:44
     |
 335 |         let channel = channel.configure_tx(pin,
led_config()).unwrap();
     |                                            ^^^
     = note:   expected reference `&TxChannelConfig`
             found type parameter `O`
note: method defined here
    -->
/home/alexis/src/cargo/git/checkouts/esp-hal-29ef8683203c9b81/223815270092/esp-hal/src/rmt.rs:1294:8
     |
1294 |     fn configure_tx(self, config: &TxChannelConfig) ->
Result<Channel<'ch, Dm, Tx>, Error>
     |        ^^^^^^^^^^^^
help: remove the extra argument
     |
 335 -         let channel = channel.configure_tx(pin,
led_config()).unwrap();
 335 +         let channel = channel.configure_tx(/* &TxChannelConfig
*/).unwrap();
     |

Some errors have detailed explanations: E0061, E0277.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `esp-hal-smartled` (lib) due to 3 previous
errors

Those errors are due to an API break introduced _after_ 1.0.0 in
esp-hal, with commit 240afa9ac996 ("RMT: Various cleanups, small API
enhancements (#4302)"). Update the configure_tx API accordingly, as
suggested by the migration guide updated in the same commit.

Signed-off-by: Alexis Lothoré <alexis.lothore@gmail.com>